//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBC.WeChat.UI.Store.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBC.WeChat.UI.Store.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /Content/images/pic/58X58.jpg 的本地化字符串。
        /// </summary>
        public static string DefaultListPicPath {
            get {
                return ResourceManager.GetString("DefaultListPicPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^([\w\-]+)(\.[\w]+)*@([\w\-]+\.){1,5}([A-Za-z]){2,4}$ 的本地化字符串。
        /// </summary>
        public static string Email_Regex {
            get {
                return ResourceManager.GetString("Email_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        public static string UI_Account {
            get {
                return ResourceManager.GetString("UI_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的Email格式 的本地化字符串。
        /// </summary>
        public static string UI_Account_ErrorEmail {
            get {
                return ResourceManager.GetString("UI_Account_ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入您的邮箱号 的本地化字符串。
        /// </summary>
        public static string UI_Account_NotNull {
            get {
                return ResourceManager.GetString("UI_Account_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string UI_Cancel {
            get {
                return ResourceManager.GetString("UI_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 看不清，换一个 的本地化字符串。
        /// </summary>
        public static string UI_ChangeValidateCode {
            get {
                return ResourceManager.GetString("UI_ChangeValidateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string UI_Confirm_Password {
            get {
                return ResourceManager.GetString("UI_Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string UI_DeliveryMethod_Action {
            get {
                return ResourceManager.GetString("UI_DeliveryMethod_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加配送方式 的本地化字符串。
        /// </summary>
        public static string UI_DeliveryMethod_AddNew {
            get {
                return ResourceManager.GetString("UI_DeliveryMethod_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string UI_DeliveryMethod_Enabled {
            get {
                return ResourceManager.GetString("UI_DeliveryMethod_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到付 的本地化字符串。
        /// </summary>
        public static string UI_DeliveryMethod_IsCod {
            get {
                return ResourceManager.GetString("UI_DeliveryMethod_IsCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配送方式名称 的本地化字符串。
        /// </summary>
        public static string UI_DeliveryMethod_Name {
            get {
                return ResourceManager.GetString("UI_DeliveryMethod_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预付 的本地化字符串。
        /// </summary>
        public static string UI_DeliveryMethod_NotCod {
            get {
                return ResourceManager.GetString("UI_DeliveryMethod_NotCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配送方式 的本地化字符串。
        /// </summary>
        public static string UI_DeliveryMethod_Title {
            get {
                return ResourceManager.GetString("UI_DeliveryMethod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string UI_DeliveryMethod_Type {
            get {
                return ResourceManager.GetString("UI_DeliveryMethod_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string UI_Disable {
            get {
                return ResourceManager.GetString("UI_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string UI_Edit {
            get {
                return ResourceManager.GetString("UI_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string UI_Enable {
            get {
                return ResourceManager.GetString("UI_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停用 的本地化字符串。
        /// </summary>
        public static string UI_Enabled_False {
            get {
                return ResourceManager.GetString("UI_Enabled_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启用 的本地化字符串。
        /// </summary>
        public static string UI_Enabled_True {
            get {
                return ResourceManager.GetString("UI_Enabled_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string UI_First {
            get {
                return ResourceManager.GetString("UI_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忘记密码？ 的本地化字符串。
        /// </summary>
        public static string UI_Forget_Password {
            get {
                return ResourceManager.GetString("UI_Forget_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入邮箱号 的本地化字符串。
        /// </summary>
        public static string UI_Input_Account {
            get {
                return ResourceManager.GetString("UI_Input_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入密码 的本地化字符串。
        /// </summary>
        public static string UI_Input_Password {
            get {
                return ResourceManager.GetString("UI_Input_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾页 的本地化字符串。
        /// </summary>
        public static string UI_Last {
            get {
                return ResourceManager.GetString("UI_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即登录 的本地化字符串。
        /// </summary>
        public static string UI_Login_Action {
            get {
                return ResourceManager.GetString("UI_Login_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败，请检查网络设置。 的本地化字符串。
        /// </summary>
        public static string UI_Login_CommonError {
            get {
                return ResourceManager.GetString("UI_Login_CommonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        public static string UI_Login_Failed {
            get {
                return ResourceManager.GetString("UI_Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在登录... 的本地化字符串。
        /// </summary>
        public static string UI_Login_Loging {
            get {
                return ResourceManager.GetString("UI_Login_Loging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微信商城后台登录 的本地化字符串。
        /// </summary>
        public static string UI_Login_Title {
            get {
                return ResourceManager.GetString("UI_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string UI_Next {
            get {
                return ResourceManager.GetString("UI_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string UI_Password {
            get {
                return ResourceManager.GetString("UI_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先输入您的密码 的本地化字符串。
        /// </summary>
        public static string UI_Password_NotNull {
            get {
                return ResourceManager.GetString("UI_Password_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string UI_Prev {
            get {
                return ResourceManager.GetString("UI_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string UI_Register {
            get {
                return ResourceManager.GetString("UI_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填写帐号信息 的本地化字符串。
        /// </summary>
        public static string UI_Register_FirstStep {
            get {
                return ResourceManager.GetString("UI_Register_FirstStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册新账号 的本地化字符串。
        /// </summary>
        public static string UI_Register_New {
            get {
                return ResourceManager.GetString("UI_Register_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string UI_Register1 {
            get {
                return ResourceManager.GetString("UI_Register1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string UI_Save {
            get {
                return ResourceManager.GetString("UI_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入要搜索的内容 的本地化字符串。
        /// </summary>
        public static string UI_SearchBgTxt {
            get {
                return ResourceManager.GetString("UI_SearchBgTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string UI_SelectAll {
            get {
                return ResourceManager.GetString("UI_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string UI_ValidateCode {
            get {
                return ResourceManager.GetString("UI_ValidateCode", resourceCulture);
            }
        }
    }
}
